### ISSUE TITLE
Project blueprint should have the new governance built in

### ISSUE THREAD

**Issue by mindthegab** [finos/project-blueprint#17]
- [x] Check if CONTRIBUTING.md works on root folder
- [x] Merge CONTRIBUTING.template.md into CONTRIBUTING.md
- [x] Update title to Software Project Blueprint
- [x] "This blueprint implements https://github.com/finos/community/tree/master/governance#open-source-software-projects" into the README.md of this repo
- [x] Arrange placeholders
- [x] The new governance allows for a governance for software projects (https://github.com/finos/community/blob/master/governance/Software-Projects/CONTRIBUTING.template.md) and one for standard projects (https://github.com/finos/community/blob/master/governance/Standards-Projects/CONTRIBUTING.standards.md).

For now, I suggest you have both of them in the blueprint and then remember to select the correct one when you instantiate a new project. 

Once you are done can you also send a pull request to Morphir and Glue to adopt it (apologizing it wasn't done in the first place)?

**Comment by mindthegab** [comment]
Scrap that, let's just make this the FINOS software project blueprint (we don't do standards so often anyway).

**Comment by mindthegab** [comment]
Actually scrap that again, I don't like that the governance would be under a .github folder. Let's bring in the governance overlord...

Hey @copiesofcopies, what was the rationale to add the governance templates in the [CONTRIBUTING.md](https://github.com/finos/community/blob/master/governance/Software-Projects/CONTRIBUTING.template.md)? I thought we modeled around NodeJS, but there I see a dedicated [GOVERNANCE.md](https://github.com/nodejs/node/blob/master/GOVERNANCE.md). 

And if the idea is to keep it one file (which I endorse), @maoo could we move CONTRIBUTING.md to the root folder? Any specific reason (e.g. integration with GH) for it to be under .github?

**Comment by mindthegab** [comment]
Hey @copiesofcopies can you let us know your thoughts here as soon as you get a chance?

**Comment by mcleo-d** [comment]
Hi @mindthegab,

This is to confirm a project's CONTRIBUTING.md can be integrated into the `root` of a project repo. This solution was taken from the following https://docs.github.com reference.

https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/setting-guidelines-for-repository-contributors

> To help your project contributors do good work, you can add a file with contribution guidelines to your project repository's `root`, `docs`, or `.github` folder. 

This completes the following task ...

- [x] Check if CONTRIBUTING.md works on root folder

**Comment by mcleo-d** [comment]
Hi @mindthegab,

The updated `governance/Software-Projects/CONTRIBUTING.template.md` has been merged into the existing Project Blueprint `CONTRIBUTING.md` by removing the previous content and replacing with the new.

If existing `CONTRIBUTING.md` content needs to be added back, I recommend taking the content from the Project Blueprint commit logs and editing before merging back. 

This completes the following task ...

- [x] Merge [CONTRIBUTING.template.md](https://github.com/finos/community/blob/master/governance/Software-Projects/CONTRIBUTING.template.md) into [CONTRIBUTING.md](https://github.com/finos/project-blueprint/blob/master/CONTRIBUTING.md)

**Comment by mcleo-d** [comment]
Hi @mindthegab,

The following `CONTRIBUTING` files have been added to the root of Project Blueprint with the expectation that the correct one will be selected when a new FINOS project is created.

### Software Projects
- [CONTRIBUTING.template.md](https://github.com/finos/community/blob/master/governance/Software-Projects/CONTRIBUTING.template.md)

### Standards Projects
- [CONTRIBUTING.standards.md](https://github.com/finos/community/blob/master/governance/Standards-Projects/CONTRIBUTING.standards.md)

This completes the following task ...

- [x] The new governance allows for a governance for software projects (https://github.com/finos/community/blob/master/governance/Software-Projects/CONTRIBUTING.template.md) and one for standard projects (https://github.com/finos/community/blob/master/governance/Standards-Projects/CONTRIBUTING.standards.md).

**Comment by mcleo-d** [comment]
@mindthegab and @maoo 

Pull Request #19 has been raised to merge the changes made to close this issue. The following items have not been included due to either being an infrastructure change or more information required.

- Update title to Software Project Blueprint (_infrastructure change_)
- Arrange placeholders (_more information required_)

James.
