### ISSUE TITLE
Embed CONTRIBUTING.md into Docusaurus microsite

### ISSUE THREAD

**Issue by maoo** [finos/project-blueprint#9]
### Description of Problem:
The `CONTRIBUTING.md` file is part of the project blueprint and includes important info regarding new contributors onboarding, which are also part of the Docusaurus microsite.

### Proposed solution:

Enhance the Docusaurus build process to create a new Docusaurus page with the `CONTRIBUTING.md` content and map it to a default site URL, ie `/contribute`.

**Comment by mcleo-d** [comment]
Hi @maoo - I've transferred this feature to the ODP backlog so it sits and is triaged with the rest of the Docusaurus work being done.

https://github.com/finos/open-developer-platform/issues/66

Please feel free to close if this works for you 👍 

James.

**Comment by maoo** [comment]
This is done, TY!
